import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:medicus/Features/Role_Based_Interface/Patients/Widgets/records/prescription.dart';

Future<Uint8List> buildPrescriptionPdf({
  required Prescription prescription,
  required String patientName,
  required String patientId,
}) async {
  final doc = pw.Document();
  final String formattedDate =
      '${prescription.date.day.toString().padLeft(2, '0')}/${prescription.date.month.toString().padLeft(2, '0')}/${prescription.date.year}';

  doc.addPage(
    pw.Page(
      pageFormat: PdfPageFormat.a4,
      build: (context) {
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('Medicus', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 4),
            pw.Text('Prescription', style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
            pw.Divider(),
            pw.SizedBox(height: 8),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Prescription ID: ${prescription.id}'),
                pw.Text('Date: $formattedDate'),
              ],
            ),
            pw.SizedBox(height: 4),
            pw.Text('Patient: $patientName (ID: $patientId)'),
            pw.SizedBox(height: 4),
            pw.Text('Doctor: ${prescription.doctorName}'),
            pw.SizedBox(height: 16),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey400),
              columnWidths: const {
                0: pw.FlexColumnWidth(3),
                1: pw.FlexColumnWidth(3),
                2: pw.FlexColumnWidth(2),
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    _cell('Medicine', bold: true),
                    _cell('Dosage', bold: true),
                    _cell('Duration', bold: true),
                  ],
                ),
                for (final medicine in prescription.medicines)
                  pw.TableRow(
                    children: [
                      _cell(medicine.name),
                      _cell(medicine.dosage),
                      _cell('${medicine.durationDays} days'),
                    ],
                  ),
              ],
            ),
            pw.SizedBox(height: 24),
            pw.Text(
              'Generated by Medicus for printing — not a substitute for the original signed prescription.',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
          ],
        );
      },
    ),
  );

  return doc.save();
}

pw.Widget _cell(String text, {bool bold = false}) {
  return pw.Padding(
    padding: const pw.EdgeInsets.all(6),
    child: pw.Text(text, style: pw.TextStyle(fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
  );
}
